const { divide } = require('./02.math');
// Generated by CodiumAI

describe('divide', () => {
  // Returns the correct result when dividing two positive numbers
  it('should return the correct result when dividing two positive numbers', () => {
    // Arrange
    const a = 10;
    const b = 2;

    // Act
    const result = divide(a, b);

    // Assert
    expect(result).toBe(5);
  });

  // Returns the correct result when dividing a positive number by zero
  it('should return the correct result when dividing a positive number by zero', () => {
    // Arrange
    const a = 10;
    const b = 0;

    // Act
    const result = divide(a, b);

    // Assert
    expect(result).toBeNull();
  });

  // Returns the correct result when dividing a negative number by a positive number
  it('should return the correct result when dividing a negative number by a positive number', () => {
    // Arrange
    const a = -10;
    const b = 2;

    // Act
    const result = divide(a, b);

    // Assert
    expect(result).toBe(-5);
  });

  // Returns the correct result when dividing a positive number by a negative number
  it('should return the correct result when dividing a positive number by a negative number', () => {
    // Arrange
    const a = 10;
    const b = -2;

    // Act
    const result = divide(a, b);

    // Assert
    expect(result).toBe(-5);
  });

  // Returns null when dividing a negative number by zero
  it('should return null when dividing a negative number by zero', () => {
    // Arrange
    const a = -10;
    const b = 0;

    // Act
    const result = divide(a, b);

    // Assert
    expect(result).toBeNull();
  });

  // Returns null when dividing zero by zero
  it('should return null when dividing zero by zero', () => {
    // Arrange
    const a = 0;
    const b = 0;

    // Act
    const result = divide(a, b);

    // Assert
    expect(result).toBeNull();
  });
});
